# Specifies what version of K8s you want to use
apiVersion: v1
# A service is used to expose your Deployment to the external access
kind: Service
metadata:
  name: psicquic-view-service
spec:
  ports:
    - port: 31230
      protocol: TCP
      # The port which will be externally exposed. Must be in the range [30000, 32767].
      nodePort: 31230
      # The port on your Deployment which it will expose
      targetPort: 8080
  selector:
    # Selects the disease-portal-view Deployment to attach the Service to
    app: psicquic-view
    # Tell K8s this wants to expose an external port
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psicquic-view-deployment
spec:
  selector:
    matchLabels:
      app: psicquic-view
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: psicquic-view
    spec:
      securityContext:
        runAsUser: 2799
        runAsGroup: 1137
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: psicquic-view
          # Pull the image which contains psicquic-view webservice and the built assets from EBI's dockerhub
          image: <CONTAINER_IMAGE>
          ports:
            # We are using psicquic-view webservice config which serves on port 8080
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: nfs-rw-volume
              mountPath: /nfs/public/rw/intact
          env:
            - name: KEYSTORE_PASSWORD
              value: "<CI_KEYSTORE_PASSWORD>"
            - name: CATALINA_OPTS
              value: "-Djavax.net.ssl.trustStore=/nfs/public/rw/intact/certificates/keystore -Djavax.net.ssl.keyStorePassword=$(KEYSTORE_PASSWORD)"
            - name: http_proxy
              value: "http://hh-wwwcache.ebi.ac.uk:3128"
            - name: https_proxy
              value: "http://hh-wwwcache.ebi.ac.uk:3128"
            - name: JAVA_OPTS
              value: "-Dhttp.proxyHost=hh-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128 -Dhttps.proxyHost=hh-wwwcache.ebi.ac.uk -Dhttps.proxyPort=3128"
      volumes:
        - name: nfs-rw-volume
          nfs:
            # URL for the NFS server
            server: hh-isi-srv-vlan1496.ebi.ac.uk
            path: /ifs/public/rw/intact
      imagePullSecrets:
        # Provided by GitLab, this allows K8s to connect to dockerhub.ebi.ac.uk
        - name: gitlab-registry
